# Generated by Django 4.1.5 on 2023-10-06 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('ticker', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('lower_bound', models.PositiveIntegerField(default=0)),
                ('upper_bound', models.PositiveIntegerField(default=0)),
                ('periodicity', models.PositiveSmallIntegerField(default=1)),
                ('actual_price', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
