# Generated by Django 4.1.5 on 2023-10-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='actual_price',
        ),
        migrations.AddField(
            model_name='stock',
            name='change',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='close',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='volume',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='lower_bound',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='upper_bound',
            field=models.FloatField(default=0.0),
        ),
    ]
