# Generated by Django 4.1.5 on 2023-10-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_monitoring', '0003_stock_change_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='change_history',
            field=models.TextField(default='[]'),
        ),
    ]
